## Styles ######################################################################

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BracesAroundHashParameters:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Layout/IndentHash:
  EnforcedStyle: consistent

# New lambda syntax is as ugly to me as new syntax of Hash.
Style/Lambda:
  Enabled: false

# A bit useless restriction, that makes impossible aligning code like this:
#
#   redis do |conn|
#     conn.hset    :k1, now
#     conn.hincrby :k2, 123
#   end
Layout/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

## Metrics #####################################################################

Metrics/MethodLength:
  CountComments: false
  Max: 15
